const images = {
  logo: '/assets/images/logo.png',
  overViewActive: '/assets/images/overViewActive.png',
  overViewInActive: '/assets/images/overViewInActive.png',
  scanInActive: '/assets/images/scanInActive.png',
  scnaActive: '/assets/images/scnaActive.png',
  userInActive: '/assets/images/userInActive.png',
  userActive: '/assets/images/userActive.png',
  supportInActive: '/assets/images/supportInActive.png',
  supportActive: '/assets/images/supportActive.png',
  complainsInActive: '/assets/images/complainsInActive.png',
  complainsActive: '/assets/images/complainsActive.png',
  workshopsActive: '/assets/images/workshopsActive.png',
  workshopsInActive: '/assets/images/workshopsInActive.png',
  loginBG: '/assets/images/loginBG.png',
  loader: '/assets/images/loader.png',
  loader2: '/assets/images/loader2.png',
  bugatti: "/assets/images/bugatti.png",
  document: "/assets/images/document.png",
  workshopImage: "/assets/images/workshopImage.png",
  Users: "/assets/images/Users.png",
  Complains: "/assets/images/Complains.png",
  Workshops: "/assets/images/Workshops.png",
  Scan: "/assets/images/Scan.png",
  barChart: "/assets/images/barChart.png",
  lineChart: "/assets/images/lineChart.png",
  carImage: "/assets/images/carImage.png",
};

export default images;
